const express=require('express');
const app=express();
app.get('/',(req,res)=>{
res.send(`<!DOCTYPE html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>HACCP FR</title><style>body{font-family:sans-serif;margin:0;background:#f4f4f4}header{background:#16a34a;color:#fff;padding:15px;text-align:center;font-weight:bold;font-size:20px}.tabs{display:flex;background:#fff}.tab{flex:1;padding:14px;text-align:center;border-bottom:3px solid #ddd}.tab.on{border-color:#16a34a;font-weight:bold}.page{display:none;padding:12px}.page.on{display:block}.card{background:#fff;padding:12px;border-radius:12px;margin:8px 0}input,select{width:100%;padding:12px;margin:5px 0;border:1px solid #ddd;border-radius:8px}button{width:100%;padding:14px;border:0;border-radius:10px;font-weight:bold;color:#fff;margin-top:6px}.g{background:#16a34a}.r{background:#dc2626}.b{background:#2563eb}</style></head><body>
<header>HYGIENE HACCP - FR</header>
<div class="tabs"><div class="tab on" id="t1" onclick="sp('frigo','t1')">FRIGO</div><div class="tab" id="t2" onclick="sp('stock','t2')">STOCK</div><div class="tab" id="t3" onclick="sp('netto','t3')">NETTOYAGE</div><div class="tab" id="t4" onclick="sp('envoi','t4')">ENVOI</div></div>
<div id="frigo" class="page on"><div class="card"><select id="f"><option>Frigo Positif</option><option>Frigo Negatif</option><option>Vitrine</option><option>Chambre Froide</option></select><input id="temp" type="number" step="0.1" placeholder="Temperature C"><button class="b" onclick="addF()">+ Ajouter releve</button></div><div id="lf"></div></div>
<div id="stock" class="page"><div class="card"><input id="n" placeholder="Produit"><input id="q" placeholder="Quantite"><input id="d" placeholder="DLC"><button class="g" onclick="addS()">+ Ajouter produit</button></div><div id="ls"></div></div>
<div id="netto" class="page"><div class="card"><input id="tn" placeholder="Tache ex: Nettoyage plan"><button class="g" onclick="addT()">+ Ajouter tache</button></div><div id="lt"></div></div>
<div id="envoi" class="page"><div class="card"><button class="g" onclick="sendWA()">Envoyer rapport WhatsApp</button><button class="r" onclick="if(confirm('Tout effacer?')){localStorage.clear();location.reload()}">Effacer tout</button></div></div>
<script>
let fr=JSON.parse(localStorage.getItem('fr')||'[]');let st=JSON.parse(localStorage.getItem('st')||'[]');let ta=JSON.parse(localStorage.getItem('ta')||'[]');
function sp(p,t){document.querySelectorAll('.page').forEach(e=>e.classList.remove('on'));document.querySelectorAll('.tab').forEach(e=>e.classList.remove('on'));document.getElementById(p).classList.add('on');document.getElementById(t).classList.add('on')}
function save(){localStorage.setItem('fr',JSON.stringify(fr));localStorage.setItem('st',JSON.stringify(st));localStorage.setItem('ta',JSON.stringify(ta))}
function addF(){let v=document.getElementById('temp').value;if(!v)return;fr.push({f:document.getElementById('f').value,t:v,h:new Date().toLocaleString()});save();render();document.getElementById('temp').value=''}
function addS(){let nn=document.getElementById('n').value;if(!nn)return;st.push({n:nn,q:document.getElementById('q').value,d:document.getElementById('d').value});save();render();document.getElementById('n').value='';document.getElementById('q').value='';document.getElementById('d').value=''}
function addT(){let nn=document.getElementById('tn').value;if(!nn)return;ta.push({n:nn,ok:false});save();render();document.getElementById('tn').value=''}
function render(){let h='';for(let i=0;i<fr.length;i++){let x=fr[i];h+='<div class=card>'+x.f+' : <b>'+x.t+' C</b> <small>'+x.h+'</small> <span onclick="fr.splice('+i+',1);save();render()" style="float:right;color:red">X</span></div>'}document.getElementById('lf').innerHTML=h;let h2='';for(let i=0;i<st.length;i++){let x=st[i];h2+='<div class=card><b>'+x.n+'</b> - '+x.q+' - DLC '+x.d+' <span onclick="st.splice('+i+',1);save();render()" style="float:right;color:red">X</span></div>'}document.getElementById('ls').innerHTML=h2;let h3='';for(let i=0;i<ta.length;i++){let x=ta[i];h3+='<div class=card><input type=checkbox '+(x.ok?'checked':'')+' onchange="ta['+i+'].ok=this.checked;save();render()"> '+x.n+' <span onclick="ta.splice('+i+',1);save();render()" style="float:right;color:red">X</span></div>'}document.getElementById('lt').innerHTML=h3}
function sendWA(){let txt='*RAPPORT HACCP '+new Date().toLocaleDateString()+'*%0A%0A*FRIGOS*%0A';for(let i=0;i<fr.length;i++){let x=fr[i];txt+='- '+x.f+' : '+x.t+'C ('+x.h+')%0A'}txt+='%0A*STOCK*%0A';for(let i=0;i<st.length;i++){let x=st[i];txt+='- '+x.n+' : '+x.q+' DLC '+x.d+'%0A'}txt+='%0A*NETTOYAGE*%0A';for(let i=0;i<ta.length;i++){let x=ta[i];txt+='- '+(x.ok?'OK':'NON')+' '+x.n+'%0A'}window.open('https://wa.me/?text='+txt,'_blank')}
render();
</script></body></html>`);
});
app.listen(process.env.PORT||10000);
