const express=require('express');
const app=express();
const html=`<!DOCTYPE html><html lang=fr><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>HACCP LUXE</title><style>body{margin:0;font-family:Arial;background:#fbf8f2}header{background:#111;color:#C9A86A;padding:18px;text-align:center;font-size:20px;border-bottom:3px solid #C9A86A}.wrap{max-width:600px;margin:auto;padding:10px}.card{background:#fff;border-radius:14px;padding:14px;margin:10px 0;box-shadow:0 3px 10px rgba(0,0,0,.1)}input,select{width:100%;padding:11px;border-radius:10px;border:1px solid #d4c4a8;margin-top:4px;box-sizing:border-box}button{width:100%;padding:13px;border-radius:10px;border:0;font-weight:bold;margin-top:8px}.gold{background:#C9A86A;color:#111}.green{background:#163524;color:#C9A86A}.tabs{display:flex;background:#111;gap:4px;padding:8px}.t{flex:1;padding:9px;border-radius:8px;background:#222;color:#C9A86A;text-align:center;font-size:12px}.t.on{background:#C9A86A;color:#111}.page{display:none}.page.on{display:block}img.pr{width:100%;max-height:180px;object-fit:cover;border-radius:8px;margin-top:6px}.notifbar{background:#C9A86A;color:#111;padding:10px;border-radius:10px;text-align:center;font-weight:bold;margin:8px 0}</style></head><body><header>HYGIENE HACCP - LUXE</header><div class=tabs><div class="t on" id=a1 onclick="go('p1','a1')">FRIGO</div><div class=t id=a2 onclick="go('p2','a2')">STOCK</div><div class=t id=a3 onclick="go('p3','a3')">NETTOYAGE</div><div class=t id=a4 onclick="go('p4','a4')">ENVOI</div></div><div class=wrap>
<div id=notifArea></div>
<div id=p1 class="page on"><div class=card><div class=notifbar>🔔 Rappel toutes les 2h</div><button class=gold onclick=enableNotif()>ACTIVER LES NOTIFICATIONS 2H</button><small id=statNotif style=display:block;text-align:center;margin-top:6px;color:#666>Notifications désactivées</small><hr><select id=f><option>Frigo Positif</option><option>Frigo Negatif</option><option>Vitrine</option><option>Chambre Froide</option></select><input id=t type=number step=0.1 placeholder="Temperature C"><input id=pf type=file accept="image/*" capture=environment><img id=fp class=pr style=display:none><button class=gold onclick=addF()>Ajouter Frigo</button></div><div id=lf></div></div>
<div id=p2 class=page><div class=card><input id=n placeholder="Produit"><input id=q placeholder="Quantite"><input id=d type=date><input id=ps type=file accept="image/*" capture=environment><img id=sp class=pr style=display:none><button class=gold onclick=addS()>Ajouter Stock</button></div><div id=ls></div></div>
<div id=p3 class=page><div class=card><input id=tn placeholder="Tache nettoyage"><input id=pn type=file accept="image/*" capture=environment><img id=np class=pr style=display:none><button class=gold onclick=addN()>Ajouter Tache</button></div><div id=lt></div></div>
<div id=p4 class=page><div class=card><button class=green onclick=sendWA()>Envoyer WhatsApp</button><button onclick="localStorage.clear();location.reload()" style=background:#111;color:#fff>Effacer tout</button></div></div></div>
<script>
let fr=JSON.parse(localStorage.getItem('f')||'[]'),st=JSON.parse(localStorage.getItem('s')||'[]'),ta=JSON.parse(localStorage.getItem('t')||'[]'),c={f:null,s:null,n:null};
let notifInterval=null;
function enableNotif(){if(!('Notification' in window)){alert('Notifications non supportées');return}Notification.requestPermission().then(p=>{if(p==='granted'){document.getElementById('statNotif').innerText='✅ Actif : Rappel toutes les 2h';localStorage.setItem('notif','on');startNotif();new Notification('HACCP LUXE',{body:'Notifications activées ! Rappel toutes les 2h'});}})}
function startNotif(){if(notifInterval)clearInterval(notifInterval);notifInterval=setInterval(()=>{let msg='⏰ RAPPEL HACCP : Contrôle frigo à faire !';document.getElementById('notifArea').innerHTML='<div class=card style=background:#111;color:#C9A86A;text-align:center;font-weight:bold>'+msg+'</div>';if(Notification.permission==='granted'){new Notification('HACCP LUXE - RAPPEL',{body:msg,requireInteraction:true})};try{let a=new Audio('https://actions.google.com/sounds/v1/alarms/beep_short.ogg');a.play()}catch(e){}},2*60*60*1000);setTimeout(()=>{if(localStorage.getItem('notif')==='on' && Notification.permission==='granted'){console.log('Test notif 10sec')} },10000)}
if(localStorage.getItem('notif')==='on'){document.getElementById('statNotif').innerText='✅ Actif : Rappel toutes les 2h';setTimeout(()=>{if(Notification.permission==='granted')startNotif()},1000)}
document.getElementById('pf').onchange=e=>{let r=new FileReader();r.onload=x=>{document.getElementById('fp').src=x.target.result;document.getElementById('fp').style.display='block';c.f=x.target.result};r.readAsDataURL(e.target.files[0])};
document.getElementById('ps').onchange=e=>{let r=new FileReader();r.onload=x=>{document.getElementById('sp').src=x.target.result;document.getElementById('sp').style.display='block';c.s=x.target.result};r.readAsDataURL(e.target.files[0])};
document.getElementById('pn').onchange=e=>{let r=new FileReader();r.onload=x=>{document.getElementById('np').src=x.target.result;document.getElementById('np').style.display='block';c.n=x.target.result};r.readAsDataURL(e.target.files[0])};
function go(p,a){document.querySelectorAll('.page').forEach(e=>e.classList.remove('on'));document.querySelectorAll('.t').forEach(e=>e.classList.remove('on'));document.getElementById(p).classList.add('on');document.getElementById(a).classList.add('on')}
function save(){localStorage.setItem('f',JSON.stringify(fr));localStorage.setItem('s',JSON.stringify(st));localStorage.setItem('t',JSON.stringify(ta))}
function addF(){let v=document.getElementById('t').value;if(!v)return;fr.push({f:document.getElementById('f').value,t:v,h:new Date().toLocaleString(),p:c.f});c.f=null;document.getElementById('t').value='';document.getElementById('pf').value='';document.getElementById('fp').style.display='none';save();R()}
function addS(){let v=document.getElementById('n').value;if(!v)return;st.push({n:v,q:document.getElementById('q').value,d:document.getElementById('d').value,p:c.s});c.s=null;['n','q','d','ps'].forEach(i=>{let e=document.getElementById(i);if(e)e.value=''});document.getElementById('sp').style.display='none';save();R()}
function addN(){let v=document.getElementById('tn').value;if(!v)return;ta.push({n:v,ok:false,p:c.n});c.n=null;document.getElementById('tn').value='';document.getElementById('pn').value='';document.getElementById('np').style.display='none';save();R()}
function R(){let h='';for(let i=0;i<fr.length;i++){let x=fr[i];h+='<div class=card><b>'+x.f+'</b> '+x.t+'C '+x.h+(x.p?'<br><img src='+x.p+' class=pr>':'')+'<br><span onclick=fr.splice('+i+',1);save();R() style=color:red>Supprimer</span></div>'}document.getElementById('lf').innerHTML=h;let h2='';for(let i=0;i<st.length;i++){let x=st[i];h2+='<div class=card><b>'+x.n+'</b> '+x.q+' DLC '+x.d+(x.p?'<br><img src='+x.p+' class=pr>':'')+'<br><span onclick=st.splice('+i+',1);save();R() style=color:red>Supprimer</span></div>'}document.getElementById('ls').innerHTML=h2;let h3='';for(let i=0;i<ta.length;i++){let x=ta[i];h3+='<div class=card><input type=checkbox '+(x.ok?'checked':'')+' onchange=ta['+i+'].ok=this.checked;save()> '+x.n+(x.p?'<br><img src='+x.p+' class=pr>':'')+'<br><span onclick=ta.splice('+i+',1);save();R() style=color:red>Supprimer</span></div>'}document.getElementById('lt').innerHTML=h3}
function sendWA(){let txt='*RAPPORT HACCP LUXE '+new Date().toLocaleDateString()+'*%0A';for(let i=0;i<fr.length;i++)txt+='- '+fr[i].f+' '+fr[i].t+'C%0A';for(let i=0;i<st.length;i++)txt+='- '+st[i].n+' '+st[i].q+' DLC '+st[i].d+'%0A';for(let i=0;i<ta.length;i++)txt+='- '+(ta[i].ok?'OK ':'')+ta[i].n+'%0A';window.open('https://wa.me/?text='+txt,'_blank')}
R();
<\/script></body></html>`;
app.get('/',(req,res)=>res.send(html));
app.listen(process.env.PORT||10000);
